### ISSUE TITLE
Landscape orientation issue

### ISSUE THREAD

**Issue by ssenior45** [viezel/NappDrawer#80]
Hello,

How do you handle landscape orientation in your apps using this module/widget?

I must be doing something basic wrong here as when I rotate to landscape on the iPhone (iOS6 and 7) my window is "pulled up" under the navigation bar by 12px. It's almost as if the navigation bar is growing (or rather, not shrinking) by 12px in landscape mode.

If I remove the widget and just use the standard navigationwindow this problem does not occur.

I know you're very busy, and I will post this to Fokke too, but just asking on the off chance you've encountered this issue and have a fix.

Many thanks in advance,
Steve 

Sample code:

index.xml

``` xml
<Alloy>
    <Widget platform="ios" id="drawer" src="nl.fokkezb.drawer">

        <Window platform="ios" role="leftWindow" id="menuWindow">
            <Label id="label">Menu</Label>
        </Window>

        <NavigationWindow id="nav" platform="ios" role="centerWindow" formFactor="handheld">
            <Window>
                <LeftNavButton>
                    <Button onClick="doClick">Menu</Button>
                </LeftNavButton>
                <Label id="label" onClick="doClick">Hello, World</Label>
            </Window>                
        </NavigationWindow>

    </Widget>
</Alloy>
```

index.js

``` javascript
function doClick(e) {
    var w=Alloy.createController('win1',{}).getView();
    $.nav.openWindow(w,{animated:true});
}

$.drawer.open();
```

index.tss

``` css
".container": {
    backgroundColor:"white"
}

"Window": {
    backgroundColor: 'white'
}

"Label": {
    width: Ti.UI.SIZE,
    height: Ti.UI.SIZE,
    color: "#000"
} 

"#drawer[platform=ios]": {
    openDrawerGestureMode: "OPEN_MODE_NONE",
    closeDrawerGestureMode: "CLOSE_MODE_ALL",
    leftDrawerWidth: 200
    ,orientationModes: [Ti.UI.PORTRAIT, Ti.UI.UPSIDE_PORTRAIT, Ti.UI.LANDSCAPE_LEFT, Ti.UI.LANDSCAPE_RIGHT]
}

"#nav[platform=ios]": {
    orientationModes: [Ti.UI.PORTRAIT, Ti.UI.UPSIDE_PORTRAIT, Ti.UI.LANDSCAPE_LEFT, Ti.UI.LANDSCAPE_RIGHT]
}
```

win1.xml

``` xml
<Alloy>

    <Window id="win1" title="Window 1" backgroundColor="blue" top="2" height="Ti.UI.FILL">
        <View id="container" backgroundColor="yellow" top="12" height="Ti.UI.FILL">    
            <Label>Hello, World Again</Label>
        </View>
    </Window>

</Alloy>
```

win1.js

``` javascript
var args = arguments[0] || {};
```
